name: Release New Version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install semantic-release
      run: npm install semantic-release@latest

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@example.com"

    - name: Create Release and Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

